# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12c1de3c7d12fc96dea208ba929b24bcf8208e4fe3f8c28fb973c99c5d29254a8acbb30ff8cb1bc3ba3df4145300a0e8cf970006b9b1eb43cac0f03fd5d47db3

test:
  secret_key_base: 98cea05ee796a59339ded6de96e912f1e3aca76f7a3808ed8a3d3281a8993d23db2efbf414ef36ede54c82dd0f3671e320868204b6cc8de25db699538b3becba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
